### ISSUE TITLE
Watch app for Tesla is frozen

### ISSUE THREAD

**Issue by qthocher** [Kemmey/Kemmey-TeslaWatch-Public#1]
I have deleted from my watch, reset my watch and when I download it comes back to the screen that says “loading”.   I used the incorrect login, and I am sure this has something to do with the freeze up, but cannot get back to a login screen. 
Thank you for your help!

Quint
![image](https://user-images.githubusercontent.com/65814617/82730408-fcfa3300-9cc4-11ea-8908-e17b6eddfe90.jpg)

**Comment by Kemmey** [comment]
I have reasoned myself into the cause of this. watchOS does not clear the keychain of the stored token after app uninstall. I will add a check for this so the app will clear the keychain if it is "dirty" after re-install. 

I will also make sure that the logout button is always accessible. 

I suspect this state is because you've logged in with an account with no associated vehicles? I will add that scenario to my test suite.

**Comment by Kemmey** [comment]
I will submit a build to TestFlight that fixes this ASAP - pending Apple beta review. Then you can revert to store build after the keychain has been cleared. Will get back to you soon

**Comment by qthocher** [comment]
That is correct- there are no vehicles on the old account.  Your customer service is spectacular!  Thank you!
