### ISSUE TITLE
Siri support?

### ISSUE THREAD

**Issue by thumbmaster** [Kemmey/Kemmey-TeslaWatch-Public#14]
Does this support using Siri to issue commands? eg., "Siri, open the frunk"

**Comment by Kemmey** [comment]
Hey

No, not in the current v1.0.4 App Store release. 

I do have it running in a private build, though. 

I'm not sure I will release it, as Siri is just so broken, I can't get it to ever register any commands. It is such a mess. While building the feature I kept saying the same sentence over and over and even though it heard me perfectly and transcribed exactly what I said, it only executes my apps command maybe one in ten tries. 

That is not something I'm willing to ship and handle support requests for on Apples behalf.

**Comment by lcharette** [comment]
WatchOS 7 will come with shortcut support on the watch. It might be an alternative to look into, as everyone could then create they own personalized shortcut and Siri commands.

**Comment by Kemmey** [comment]
Yes - absolutely - much more interesting. Though, my app is watch-only, and as I understand it, shortcuts will have to be created on the phone, but can then execute on the watch. So I don't think a watch-only app will be able to expose shortcut actions on the phone...

I'll have to look into that. 

But another solution would be to expose a lot of different complications - and possibly allow a tap on a complication to not only open the app - but also to execute a designated action. That way, you could have a toggle lock state complication or a toggle charging complication - and they would then also show their corresponding status values - I'm much more in favor of that solution (already working on it, in fact, though you guys won't see it until the fall :-D )

**Comment by BjornB2** [comment]
I know there are apps (like Carrot weather) where you can add multiple complications, and the actual location sets the function of the complication. That way you could make a corner complication for a dedicated action like toggle AC, and have a circular complication to open the app.
By the way, my experience with Siri is quite ok. I'd love to be able to issue some simple commands like 'unlock my Tesla' and 'Turn Tesla Climate contol on'.

**Comment by Kemmey** [comment]
I did have that form of complication support actually implemented and working, but never shipped it because Apple announced proper multi complication support with watchOS 7. No reason to ship a stopgap solution. 

As this app does not have an iOS counterpart, it's going to be very limited in the set of Siri intents it can support. Currently with 1.0.7 beta you can ask if car is locked. Lock or unlock it and ask for range / battery level. And ask it to signal with lights or horn. That's it. That's all the "car" intents Apple supports natively. Anything else would have to be via shortcuts donations, which require iOS to allow you to setup custom sentences for :-(

**Comment by frjps** [comment]
While I love this app, I don’t want to receive the plethora of emails that I get but even though I have unsubscribed from this thread, I keep getting the emails! Do you know how to stop that? Thanks!

**Comment by BjornB2** [comment]
It's below the email and on the website (desktop version) it's in the right column.
<img width="357" alt="Schermafbeelding 2020-09-11 om 15 16 13" src="https://user-images.githubusercontent.com/3328086/92930017-c3029780-f441-11ea-936a-9032299d15fc.png">

**Comment by BjornB2** [comment]
> I did have that form of complication support actually implemented and working, but never shipped it because Apple announced proper multi complication support with watchOS 7. No reason to ship a stopgap solution.
> 
> As this app does not have an iOS counterpart, it's going to be very limited in the set of Siri intents it can support. Currently with 1.0.7 beta you can ask if car is locked. Lock or unlock it and ask for range / battery level. And ask it to signal with lights or horn. That's it. That's all the "car" intents Apple supports natively. Anything else would have to be via shortcuts donations, which require iOS to allow you to setup custom sentences for :-(

There is a bit of a bug for me with the Siri support. When I try a command it tells me that I need to give access to watch app for Tesla on my iPhone. Of course that is not possible since it's a watch only app, but it is possible to give access on the watch settings app -> siri.

**Comment by Kemmey** [comment]
Yub - just another bug on the huge steaming pile of stuff that Apple doesn't care about. Support for independent watch apps is abysmal - Apple seemingly doesn't care. Continuity keyboard being the worst offender...

**Comment by thumbmaster** [comment]
I haven't used Siri with this app but you can enable it on the watch itself. Go to Settings > Siri > Use with Siri.

**Comment by BjornB2** [comment]
That's what I said in my last sentence 😉

**Comment by Kemmey** [comment]
Oh - and next question - shouldn't watchOS surface an OS dialog prompting the user for Siri access on first request? Yub, IT SHOULD! But it doesn't! Because that would normally be handled by the iOS app requesting that and showing the OS dialog - but again, Apple doesn't care and just shrugs it off... sigh

**Comment by thumbmaster** [comment]
LOL Sorry for jumping to conclusions.
BTW, I just tested it with Siri and so far (the limited capabilities) work great!

**Comment by frjps** [comment]
Yes...it says that I’m not subscribed but I am still receiving these emails (and proof of this one shows that!).

**Comment by Goldbli** [comment]
I love this app! Much easier and more intuitive than the Tesla Remote app which I’ve had for a couple of years. One question: I am able to use Siri with basic commands to my watch (“unlock the car”).  I would like to start the climate remotely; is there currently a way to get Siri to do that? I have looked through these conversations and do not see it. I see seat heaters in the phone app, but could not find anything else like this. Thanks in advance!

**Comment by Kemmey** [comment]
Hey @Goldbli 

No, unfortunately not at this time. I still have that on my list of things to implement, but have not gotten around to doing it. Mostly because it's such a huge localization task providing sample sentences in all supported languages for all combinations of commands...

**Comment by Goldbli** [comment]
Hi and thanks for your response.  Thanks for the awesome app!  So happy to have dumped Tesla Remote.

On Feb 8, 2021, at 12:45 PM, Kim Hansen <notifications@github.com> wrote:


Hey @Goldbli <https://github.com/Goldbli>
No, unfortunately not at this time. I still have that on my list of things to implement, but have not gotten around to doing it. Mostly because it's such a huge localization task providing sample sentences in all supported languages for all combinations of commands...
