### ISSUE TITLE
App does not work with watch iOS 7

### ISSUE THREAD

**Issue by kwood233** [Kemmey/Kemmey-TeslaWatch-Public#148]
This application does not work on watch iOS 7 and did not migrate with new Apple Watch 6.

**Comment by Kemmey** [comment]
It does work - there are a few bugs in current AppStore release, but they have been fixed in upcoming update. 

When you migrated to your watch, Apple did not ensure to re-install any independent watch apps. Which is a bug by Apple. 

You need to manually install it again from the AppStore directly on the watch. Also this, is a bug by Apple, that you can't do it from your phone. 

https://github.com/Kemmey/Kemmey-TeslaWatch-Public/issues/5#issuecomment-658742571

**Comment by kwood233** [comment]
Perfect. Worked well in watch store. Thanks.
