### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by VAA54** [Kemmey/Kemmey-TeslaWatch-Public#276]
Since yesterday my watch for Tesla app stopped working. With message response code 400 bad request

**Comment by Kemmey** [comment]
Hey @VAA54 

Yeah, please see my tweet here:

https://twitter.com/watchfortesla/status/1355859741067665408?s=21

ADVISORY: On Friday Tesla turned off legacy authentication. Now only MFA login will be supported. Impact is that login HAS to happen on iOS and then be transferred to the watch. It is NO LONGER possible to login directly on the watch. Please install the iOS app if missing. Thanks!

This will affect all third party apps from Friday going forward that have not updated the login mechanism. 

Fortunately I did update Watch for Tesla three months ago, but you have to install the iOS companion app, since the login now require the use of a web browser, which is not available on the watch. 

Please install the app from here - it's the same purchase as the watch app, so not a new or additional purchase. 

https://apps.apple.com/dk/app/watch-app-for-tesla/id1512108917

Let me know if you have further questions or run into troubles. 

Cheers,

Kim

**Comment by VAA54** [comment]
Great Kim. All working now. Many thanks.
