### ISSUE TITLE
Can not login since 6/25 pm 

### ISSUE THREAD

**Issue by Kenz300** [Kemmey/Kemmey-TeslaWatch-Public#28]
After purchasing the app I logged in fine. So after that I tried to add the picture of my car. It failed.
Ever since yesterday I am unable to login in to the application at all.
I rebooted the watch and the phone still no luck. 
I even deleted the app and started all over and it still will not login.
I went to my Tesla account and was able to login fine so it is not locked out from their end.

**Comment by Kemmey** [comment]
Does the app crash on startup or does it show the login screen properly?

Are you logging in with user/pass or token?

When the app fails login, what does the message state - just plain "error occurred"?

**Comment by Kenz300** [comment]
I just tried it again and this time it worked.

Not sure what changed. Was there any reset on your end ? 

Not ready to try the picture again though. There has to be an easier way to add the picture.

Stock picture file of Model3 in various colors might be easier.

Adding the url is a pain.

**Comment by Kemmey** [comment]
You might have been rate limited by the Tesla api - it happens sometimes if you try more than a few times. 

Please note that I do not run any infrastructure - I never see your credentials or network traffic - it's all directly between your watch and the Tesla servers.

**Comment by Kemmey** [comment]
Regarding the background image - yeah - umm... Those are Tesla intellectual property - I can't use those pictures, as I do not have the rights to them. 

I can't control what url you might enter though - so that's kind of my gray-zone workaround...

You might also consider copying an iCloud share url to any of your own photos - so you can have any background really...

But being able to copy/paste reliably into the continuity keyboard really is essential for the feature. I find that the three-finger-tap gesture mostly works, though, as long as the notification does show up, and the keyboard properly connects...

**Comment by Kenz300** [comment]
Thanks
