### ISSUE TITLE
setting "allow wake in background" resets to "on"

### ISSUE THREAD

**Issue by jgrendahl77** [Kemmey/Kemmey-TeslaWatch-Public#3]
I cannot determine what event causes this setting to return to the "on" state after being turned off, but somehow it does. I have turned this "off" twice now since installing the app and both times it has switched itself back to "on." This causes my Tesla to wake up once an hour. Turning the setting "off" solves the wake issue, but the setting somehow goes back to "on" through the period of a day. Please check this.

**Comment by Kemmey** [comment]
You are absolutely right - I literally checked in fix 30 seconds before getting notified of your submission here. 

It is reset on cold-launch of app - so as long as app remains in memory on the watch, the setting is respected. 

I'll have this fixed in 1.0.3. 

If you want it fixed straight away, you can join the public Test Flight beta test at https://testflight.apple.com/join/FdzFOLZv - build is processing as I type this.

**Comment by jgrendahl77** [comment]
I pulled it down via testflight and installed...can't tell though if it updated on the watch...no way that I can find to see the version installed on watch. I reinstalled the app in the AppStore on my watch via account->purchased->download from cloud. Maybe add the version/build on the setting screen of the app?

**Comment by Kemmey** [comment]
Good point - I just added version and build to the about screen.
