### ISSUE TITLE
Run a shortcut with Siri

### ISSUE THREAD

**Issue by kleine100** [Kemmey/Kemmey-TeslaWatch-Public#303]
Hi Kim,
Do you plan to add more short cuts that can be run with Siri (only open and close trunk is available as far as I can see)?

Would be great if all short cuts can be run with Siri :-)

Really enjoying the app - keep up the great work 🙌🏻👍🏻

**Comment by Kemmey** [comment]
Hey @kleine100 

All current shortcuts actions can be triggered by Siri - but you'll have to configure them first. This experience will be much improved with 1.1.6, where this can be done directly in the app:

https://testflight.apple.com/join/FdzFOLZv

For 1.1.5 you'll have to go to the Shortcuts app and add each action to a new shortcut. Search for Tesla to see all donated actions. The name you assign each shortcut, will be the trigger phrase for Siri. 

Cheers,

Kim

**Comment by kleine100** [comment]
Thanks Kim. Yesterday when I tried to add short cuts via the Apple ‘Short Cut’ app I couldn’t add a custom phrase for Siri. Turns out it’s because the Apple app only shows the most frequently used short cuts 🙄

Will definitely try the 1.1.6 beta to enjoy the improved experience. 

Thanks again 👍🏻

**Comment by Kemmey** [comment]
@kleine100 you should be able to control which folders of shortcuts are synced to the watch - but I was not aware that for Siri to work from the watch, that the shortcut should also be synced... I'll have to experiment with that. It's a bit of a mess to have all the shortcuts that basically only exist because of Siri mixed in with the shortcuts that you've made yourself that you actually want to trigger with the shortcuts app or widget...
