### ISSUE TITLE
Would Unlocking door while charging unlock charge port and interrupt charging?

### ISSUE THREAD

**Issue by teslaman2** [Kemmey/Kemmey-TeslaWatch-Public#33]
Sometimes you may want to unlock to get into the vehicle to take something out that you forgot to take with you, but not interrupt the charging. If unlocking the door also unlocks the charge port, would it disconnect the charging?

**Comment by Kemmey** [comment]
Hey @teslaman2 

You just sent me on somewhat of a wild goose chase! :-D 

Ok, here's the thing: 

If vehicle is currently charging and you tap the main unlock button, it will only unlock the car and not interrupt charging

If vehicle is currently not charging and you tap the main unlock button, it will unlock the charge port and the vehicle

If the vehicle is currently charging and you tap open port from either force touch menu or controls menu, it will stop charging and unlock the port

If the vehicle is not currently charging and you tap open port from either force touch menu or controls menu, it will only unlock the port

Phew - ok, so that's all fine and good and as it's supposed to be. 

This is where it gets fishy - if you have scheduled departure activated - and you run into the same bug I just did - and many others have observed in various forums - you won't be able to stop charging if vehicle is currently charging. Not from my app with any of the controls, and not from the tesla app on phone either! It states that it stopped charging (my app will do the same, in anticipation of success) but after a few seconds it will revert to show charging, and it will not actually have stopped anything. Only if you while the tesla app states charging stopped and it briefly shows the unlock port, tap the unlock port, you can then yank out the charge cable, thus interrupting the charge...

Completely reproducible. Disable scheduled departure, and everything works perfectly...

**Comment by teslaman2** [comment]
Thank you so much for your quick and thorough response!
