### ISSUE TITLE
App will not install on Watch

### ISSUE THREAD

**Issue by DLS4** [Kemmey/Kemmey-TeslaWatch-Public#331]
I had to erase my watch to do the latest update but now I cannot install the app on my watch.  I'm using the phone to install.  I also tried to install via the store app on the watch but it wants me to pay $9.99 again.  I tried to look under my purchases but on the watch it doesn't show.  I does show on the phone that I purchased.

**Comment by DLS4** [comment]
I just tried the repurchase and and it recognized that I had purchased it in the past.

**Comment by Kemmey** [comment]
@DLS4 yeah - I was going to say - the app store experience is not all that great in that regard. But yeah - once you do tap purchase again, it'll recognize you already bought it and offer to download for free...

Did you eventually re-install directly on the watch? Is the app working still? Usually, in order to get the phone and watch to properly communicate, the watch app should be installed from the phone. The watch app is still fully independent, but during login the phone app is needed.

**Comment by DLS4** [comment]
I did get it working. But I think because I had it installed on the iPhone. 

> Best Regards, 
>  
> Don S.
