### ISSUE TITLE
R in Square Icon- what does this mean?

### ISSUE THREAD

**Issue by dionysussc** [Kemmey/Kemmey-TeslaWatch-Public#437]
There is now an icon between the battery SOC indicator and range indicator.  The icon is a square with a capital R inside.  This is new and I have no idea what it means.  Any tips, insight, answers?  
![08447F4A-AAD1-4E36-A7DF-C831442C5DB0](https://user-images.githubusercontent.com/95154892/143727322-4c1a2b54-72ff-4a93-8e84-569501a7763a.jpeg)

**Comment by Kemmey** [comment]
Yeah - those indicators are new, as I got a lot of support requests because users changed the settings and could not understand why this app shows different range than official app or car - so I added indicators for how the range is currently calculated. 

Check the new help and hints section in settings!

![image](https://user-images.githubusercontent.com/4688084/143732622-c47d41f9-cf1c-47f6-994d-9e3a5785e324.jpeg)

![image](https://user-images.githubusercontent.com/4688084/143732625-3cf966a3-c261-40dd-a2aa-553218f8fddf.jpeg)

**Comment by dionysussc** [comment]
Awesome!  Thanks for the info 👍
