### ISSUE TITLE
Not letting me sign in, using iOS 14 beta

### ISSUE THREAD

**Issue by normr1** [Kemmey/Kemmey-TeslaWatch-Public#57]
I am not able to sign into the app on my watch, I input my Tesla credentials correctly but will not log in

**Comment by Kemmey** [comment]
Hey, I don't think this is ios14 related, or it would have been more widespread. 

A few things to try. 

First, verify that your account is not locked out from too many failed attempts, by logging in at Tesla.com

Then please try typing out your password in a notes document and use copy paste with the continuity keyboard on your phone to ensure there are no typing mistakes (I know - but for instance double-tap for period results in two spaces on ios13 - may not be fixed in ios14)

Finally, try generating a token with shortcuts to entirely cut the app out of the auth flow: https://www.watchfortesla.com/blog/login-with-token/

Let me know how that goes.
