### ISSUE TITLE
Bought App on Iphone but it's not downloading on Apple Watch

### ISSUE THREAD

**Issue by iguido24** [Kemmey/Kemmey-TeslaWatch-Public#68]
Hi!

I bought the app on my iPhone app store but it never downloaded to my phone. When I check the app store in my watch it says I need to pay again. 

Please help!

**Comment by Kemmey** [comment]
Hey @iguido24 

This is really an AppStore issue and not an issue with this particular app. You should generally contact Apple AppStore support for help with purchases, as developers have zero control over the AppStore experience. That's why Apple takes a 30% cut of all sales - to ensure the infrastructure and experience is working properly. They don't do a very good job at that, in my humble opinion, as purchasing standalone watch apps is horribly broken, as you've noticed. 

Two things to try - first ensure you're logged in to the same AppStore account on your phone and watch - sometimes you're not properly logged in to the AppStore on the watch. 

If both app stores are properly logged in, then first go to your account, purchases in the AppStore app on the watch itself and check for the app in the list of recent purchases and download from there. If it's not there, do as you did previously and search for the app on the watch AppStore and "buy" it again. Apple will never charge you twice on the same account - it's more likely that the purchase just didn't sync. 

If you are charged twice, it's will have to be on two different accounts, and you should just contact Apple and get one of the purchases refunded. 

Let me know how that goes.

**Comment by Kemmey** [comment]
Also, see https://github.com/Kemmey/Kemmey-TeslaWatch-Public/issues/5#issuecomment-658742571
