### ISSUE TITLE
Text color in Open Frunk confirmation

### ISSUE THREAD

**Issue by joetomasone** [Kemmey/Kemmey-TeslaWatch-Public#74]
When you open the Frunk, the confirmation text "Open Frunk" is in red.   This is very difficult to read in bright sun outdoors.   Can that text color be changed to something brighter like Orange or Yellow?

BTW - GREAT app.

**Comment by Kemmey** [comment]
@joetomasone Thanks! :-D 

The red text is an operating system color for "non-reversible action". I use that for actions that - at least on model 3 without power trunks - can't be reversed from the app. 

It would be super bad to open your frunk by accident when you can't get to the car to close it. That's why I have the confirmations. 

I might make them configurable from settings at some point - because all other models or even 3's with actuators can reverse the action.

**Comment by joetomasone** [comment]
I’m not suggesting to get rid of the confirmation prompt - just make it more visible.  

When I am trying to intentionally open the frunk while walking to the car outdoors, it becomes hard to see the prompt to actually confirm the request.   Yellow would likely be much easier to see yet still convey the urgency of the confirmation.

**Comment by Kemmey** [comment]
Yeah - and that's fair - but the OS determines the red color in that case. It would go against the HIG to change the color - even if I could.

**Comment by joetomasone** [comment]
Ah, gotcha.    OK, I'll close this then.   Thanks for the info.    Again - great app.
