### ISSUE TITLE
Upload problem

### ISSUE THREAD

**Issue by poweroftwo2** [Kemmey/Kemmey-TeslaWatch-Public#79]
I have the common family sharing problem where another family member is asked to pay for the app although it was already purchased. I deleted the app per Apple support and cannot re-download, as the app doesnt have the download from cloud icon.

**Comment by Kemmey** [comment]
Hey

Yeah, that's really super annoying! The lease leave feedback if you get the family sharing solved. 

But re-downloading is easy to fix - you HAVE to do it from the watch itself. It's a quirk of watch-only apps, unfortunately. Had I known that independent watch apps were so broken by Apple, I'd have made it a part of a dummy companion iOS app. Unfortunately - again because Apple and no other reason - once published to the store as independent app, I can't ever add a companion app :-(

Please launch the App Store app on the watch and search for Tesla - it should show up in the first few results - then you can tap the cloud+arrow icon to re-download...

Please let me know if that worked. 

There's a couple posts with screenshots on closed issues already - I'm currently camping so I don't have a god enough connection to send new screenshots now :-D

**Comment by poweroftwo2** [comment]
Thanks for the quick response! A possibility is for both users to buy the app and have Apple refund the cost of the second app purchase. 

Elaine

**Comment by Kemmey** [comment]
Wow! Really? So they flat out admit that family sharing of independent watch apps is broken?

I might have to disable family sharing for the app, if it's broken by Apple anyway...

**Comment by poweroftwo2** [comment]
Family share solution: it turns out the app says purchased for the other family members but if you press buy, then it says it is already purchased!
