### ISSUE TITLE
two issues - (1) range on complication (2) location doesnt appear

### ISSUE THREAD

**Issue by balyesh** [Kemmey/Kemmey-TeslaWatch-Public#8]
Hello,

Awesome app...just a couple of bug fixes to make it perfect. 

Two issues:

1. on the complications screen the app shows battery at 37 but when you click 37 the tesla watch app shows 110 miles...how do i fix this? i already tried to reset app.
-is the complication showing percentage where the detail is showing range? if so, can you make an option for range on complication? its confusing from UX perspective especially when there is no `%` 

2. I can't seem to find the Location button in settings that is displayed on the app store images as an option.

Best,

Ben

**Comment by Kemmey** [comment]
Hi @balyesh 

1. The modular circular closed gauge complication only has space for two digits and the gauge. Because of that, that particular complication can only show SoC in percent. I could switch to an open gauge and include the percent sign at the bottom. But SoC in range will never fit. If compatible with your watch usage, try the graphic corner complication - I find that to be the most useful as a surprising amount of data will fit in that (charging indicator, SoC in percent as gauge, SoC in vehicle-configured unit, charge time remaining with live countdown and sentry mode active indicator)

2. You'll find that button if you tap on the show controls button - then all the additional controls will be revealed.

**Comment by Kemmey** [comment]
@balyesh hey - I'm happy to report that I've finally solved the location not showing up bug - I did not account for negative lattitude or longitude! Sorry - it's fixed in current beta, if you wish to verify: https://testflight.apple.com/join/FdzFOLZv
