### ISSUE TITLE
Keyless 3

### ISSUE THREAD

**Issue by hrustar** [Kemmey/Kemmey-TeslaWatch-Public#9]
I can’t understand how to make keyless drive or location work. Neither appear under controls as shown in the app images in the App Store. Also, I can’t add my Apple Watch as a Bluetooth device. I purchased the app first and foremost for this feature. Thanks.

**Comment by Kemmey** [comment]
Hi, 

in order to make keyless drive function, you have to enable it by accessing the about screen, which you access by tapping the grey app logo at the bottom of the main screen. Then you can enable keyless drive, after having entered your password. 

Please be very much aware about the disclaimers - keyless drive does NOT work via bluetooth, but require internet connectivity on both your watch and your car AT ALL TIMES. Do NOT drive into the desert and leave your car, or you will not be able to drive any further without a backup key. In fact, never EVER drive anywhere without a proper backup key. The store listing should already make this clear. 

The location action appears only when the app has an actual location for your car. For some reason your car is not reporting its current location through the Tesla API. Can you verify that you can see the car location in the official Tesla app?

That by the way applies to keyless drive as well - can you verify that you can enable keyless drive with the official Tesla app? It also has to be activated in the car, as well as mobile access.

**Comment by hrustar** [comment]
THANK YOU.

Keyless start now works. 

Location still not appearing. It does appear in the official Tesla app though. 

I will revise my App Store review.

**Comment by Kemmey** [comment]
Hey,

Did the location ever start to work?

Would you be willing to join a TestFlight beta where I can output some debug info to get to the bottom of this?

**Comment by hrustar** [comment]
I’d be happy to join the TestFlight beta group. As for location, it still does not work.

**Comment by Kemmey** [comment]
Awesome - thank you!

Could you join this testflight: https://testflight.apple.com/join/qcWIFpo5 

And report back what the values of lat and lon are - you don't have to be specific, just if they're 0 or not :-D

**Comment by Kemmey** [comment]
@hrustar hey - I'm happy to report that I've finally solved the location not showing up bug - I did not account for negative lattitude or longitude! Sorry - it's fixed in current beta, if you wish to verify: https://testflight.apple.com/join/FdzFOLZv

**Comment by hrustar** [comment]
Awesome news. I’m finally back from a vacation and able to use your app again. Thanks!
